# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Final Certification

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn clean test

      - name: Set build status
        if: ${{ success() }}
        run: echo "BUILD_STATUS=SUCCESS" >> $GITHUB_ENV

      - name: Set build status failure
        if: ${{ failure() }}
        run: echo "BUILD_STATUS=FAILURE" >> $GITHUB_ENV

        # Установка Allure Commandline
      - name: Install Allure commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.35.1/allure-2.35.1.tgz
          tar -xzf allure-2.35.1.tgz
          sudo mv allure-2.35.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      # Сохраняем историю из предыдущего отчёта
      - name: Download previous Allure history
        uses: actions/download-artifact@v4
        with:
          name: allure-history
          path: target/allure-results/history
        continue-on-error: true  # если истории ещё нет — не падаем

        # Генерация HTML-отчета из результатов
      - name: Generate Allure HTML report
        run: |
          ls -la target/allure-results
          allure generate target/allure-results --clean -o target/allure-report

      # Загружаем папку history из отчёта как артефакт, чтобы использовать в следующий раз
      - name: Upload Allure history
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: target/allure-report/history

        # Загрузка отчета как артефакт
      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

      # Публикация Allure отчета в Github Pages
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/allure-report